<?php
/**
 * Insert All Herbs Script
 * This script will insert all 63 herbs into the database
 * It will skip any herbs that already exist
 */

require_once __DIR__ . '/config/config.php';

try {
    $dsn = "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=utf8mb4";
    $db = new PDO($dsn, DB_USER, DB_PASS);
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // Count current herbs
    $stmt = $db->query("SELECT COUNT(*) as count FROM herbs");
    $beforeCount = (int)$stmt->fetch(PDO::FETCH_ASSOC)['count'];
    
    // All 63 herbs data
    $herbs = [
        ['Chamomile', 'Matricaria chamomilla', 'Chamomile is a gentle herb known for its calming and soothing properties. It has been used for centuries to promote relaxation, improve sleep quality, and support digestive health.', '/images/herbs/chamomile.jpg', 'Tea: Steep 1-2 teaspoons of dried flowers in hot water for 5-10 minutes. Tincture: 1-4 ml three times daily. Topical: Use as a compress for skin irritation.', 'Tea: 1-4 cups daily. Tincture: 1-4 ml (20-80 drops) three times daily. Safe for most adults when used appropriately.', 'May cause allergic reactions in people sensitive to ragweed. Not recommended during pregnancy without medical supervision. May interact with blood-thinning medications.'],
        ['Peppermint', 'Mentha piperita', 'Peppermint is a refreshing herb with powerful digestive benefits. It helps relieve indigestion, bloating, and can soothe headaches when applied topically.', '/images/herbs/peppermint.jpg', 'Tea: Steep 1 teaspoon of dried leaves in hot water for 5-7 minutes. Essential oil: Dilute and apply topically for headaches. Capsules: Follow product instructions.', 'Tea: 1-3 cups daily between meals. Essential oil: Use sparingly, always diluted. Capsules: Typically 0.2-0.4 ml of enteric-coated capsules.', 'May cause heartburn in some individuals. Not recommended for infants or young children. Essential oil should never be ingested undiluted.'],
        ['Ginger', 'Zingiber officinale', 'Ginger is a warming spice with anti-inflammatory and digestive properties. It is particularly effective for nausea, motion sickness, and inflammatory conditions.', '/images/herbs/ginger.jpg', 'Tea: Simmer 1-2 slices of fresh ginger root in water for 10-15 minutes. Fresh: Chew small pieces. Powder: Add to food or make tea. Capsules: Follow product instructions.', 'Fresh: 1-2 grams daily. Tea: 2-4 cups daily. Powder: 1-2 grams. Capsules: 500-1000 mg up to 4 times daily for nausea.', 'May interact with blood-thinning medications. Use cautiously if you have gallstones. High doses may cause heartburn. Not recommended during pregnancy without medical advice.'],
        ['Turmeric', 'Curcuma longa', 'Turmeric contains curcumin, a powerful anti-inflammatory compound. It is used for joint pain, inflammation, and overall wellness support.', '/images/herbs/turmeric.jpg', 'Tea: Simmer 1 teaspoon of powder in water with black pepper for 10 minutes. Golden milk: Mix with warm milk and honey. Capsules: Follow product instructions. Add to food.', 'Powder: 1-3 grams daily. Curcumin supplements: 500-1000 mg daily. Best absorbed with black pepper and fat.', 'May interact with blood-thinning medications and diabetes medications. May increase risk of kidney stones in susceptible individuals. Use cautiously if you have gallbladder issues.'],
        ['Lavender', 'Lavandula angustifolia', 'Lavender is renowned for its calming and relaxing effects. It helps reduce anxiety, improve sleep, and can be used topically for skin conditions.', '/images/herbs/lavender.jpg', 'Tea: Steep 1-2 teaspoons of dried flowers in hot water for 5-10 minutes. Essential oil: Use in aromatherapy or dilute for topical use. Pillow sachets: Place dried flowers in a sachet.', 'Tea: 1-2 cups daily, especially before bedtime. Essential oil: 2-4 drops in diffuser or diluted for topical use. Safe for most adults.', 'Essential oil should not be ingested. May cause skin irritation if not properly diluted. Use cautiously during pregnancy.'],
        ['Echinacea', 'Echinacea purpurea', 'Echinacea is a popular immune-supporting herb, commonly used to help prevent and shorten the duration of colds and flu.', '/images/herbs/echinacea.jpg', 'Tea: Steep 1-2 teaspoons of dried root or leaves in hot water for 10-15 minutes. Tincture: 2-4 ml three times daily. Capsules: Follow product instructions.', 'Tea: 2-4 cups daily at first sign of symptoms. Tincture: 2-4 ml (40-80 drops) three times daily. Capsules: 300-500 mg three times daily. Use for short periods (1-2 weeks).', 'Not recommended for people with autoimmune disorders. May interact with immunosuppressant medications. Not for long-term use. Avoid if allergic to ragweed.'],
        ['Garlic', 'Allium sativum', 'Garlic is a powerful herb with cardiovascular and immune benefits. It has antimicrobial properties and supports heart health.', '/images/herbs/garlic.jpg', 'Fresh: Crush or chop and let sit 10 minutes before consuming. Cooked: Add to meals. Supplements: Aged garlic extract or capsules. Oil: Use in cooking.', 'Fresh: 1-2 cloves daily. Supplements: 600-1200 mg daily of aged garlic extract. Best consumed raw or lightly cooked for maximum benefits.', 'May increase bleeding risk, especially with blood-thinning medications. May cause digestive upset in some people. Strong odor may be unpleasant.'],
        ['Aloe Vera', 'Aloe barbadensis', 'Aloe vera is best known for its skin-healing properties, but it also supports digestive health when taken internally.', '/images/herbs/aloe-vera.jpg', 'Topical: Apply fresh gel directly to skin. Internal: Use processed aloe vera juice (not raw latex). Gel: Extract from fresh leaves.', 'Topical: Apply as needed to affected areas. Internal juice: 30-60 ml daily (use processed, not raw latex).', 'Internal use of raw aloe latex can be dangerous. Only use processed aloe products for internal use. May cause digestive upset. Not recommended during pregnancy.'],
        ['Green Tea', 'Camellia sinensis', 'Green tea is rich in antioxidants and provides gentle energy support. It supports cardiovascular health and overall wellness.', '/images/herbs/green-tea.jpg', 'Tea: Steep 1 teaspoon of leaves in hot (not boiling) water for 2-3 minutes. Can be consumed hot or cold. Matcha: Whisk powder in water.', '2-3 cups daily. Contains caffeine (20-45 mg per cup), so monitor intake. Best consumed between meals.', 'Contains caffeine - may cause insomnia, anxiety, or jitteriness in sensitive individuals. May interact with certain medications. Limit during pregnancy.'],
        ['Valerian Root', 'Valeriana officinalis', 'Valerian is a powerful sleep aid and anxiety reducer. It has sedative properties that help promote restful sleep.', '/images/herbs/valerian.jpg', 'Tea: Steep 1-2 teaspoons of dried root in hot water for 10-15 minutes. Tincture: 1-3 ml before bedtime. Capsules: Follow product instructions.', 'Tea: 1 cup 30-60 minutes before bedtime. Tincture: 1-3 ml (20-60 drops) before bed. Capsules: 300-600 mg before sleep.', 'May cause drowsiness - do not drive or operate machinery. May interact with sedatives and alcohol. Not recommended for long-term daily use. Some people may experience opposite effects.'],
        ['Cinnamon', 'Cinnamomum verum', 'Cinnamon helps regulate blood sugar and has anti-inflammatory properties. It is warming and supports digestive health.', '/images/herbs/cinnamon.jpg', 'Tea: Steep 1 teaspoon of powder or a stick in hot water for 10 minutes. Add to food and beverages. Supplements: Follow product instructions.', 'Powder: 1-2 grams daily (about 1/2 to 1 teaspoon). Supplements: 500-1000 mg daily. Best consumed with meals.', 'High doses may cause liver damage. Use Ceylon cinnamon rather than cassia for regular consumption. May interact with diabetes medications.'],
        ['Holy Basil (Tulsi)', 'Ocimum tenuiflorum', 'Holy basil, or Tulsi, is an adaptogenic herb that helps the body manage stress. It supports immune function and overall resilience.', '/images/herbs/holy-basil.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 5-10 minutes. Tincture: 2-4 ml daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml (40-80 drops) daily. Capsules: 400-600 mg daily. Can be used long-term.', 'May lower blood sugar - monitor if diabetic. May slow blood clotting. Use cautiously before surgery. Generally safe for most adults.'],
        ['Ashwagandha', 'Withania somnifera', 'Ashwagandha is an adaptogenic herb that helps the body manage stress, supports energy levels, and promotes overall vitality.', '/images/herbs/ashwagandha.jpg', 'Powder: Mix 1/2 to 1 teaspoon in warm milk or water. Capsules: Follow product instructions. Tincture: 2-4 ml daily.', 'Powder: 1-3 grams daily. Capsules: 300-600 mg daily. Tincture: 2-4 ml daily. Best taken with food. Can be used long-term.', 'May interact with thyroid medications. May lower blood sugar. Use cautiously if you have autoimmune conditions. Not recommended during pregnancy.'],
        ['Dandelion', 'Taraxacum officinale', 'Dandelion supports liver health and digestion. It acts as a gentle diuretic and supports detoxification processes.', '/images/herbs/dandelion.jpg', 'Tea: Steep 1-2 teaspoons of dried root or leaves in hot water for 10-15 minutes. Fresh: Use young leaves in salads. Tincture: 2-4 ml daily.', 'Tea: 2-3 cups daily. Root tea: Best for liver support. Leaf tea: Best for gentle diuretic effect. Tincture: 2-4 ml daily.', 'May cause allergic reactions in people sensitive to ragweed. May interact with diuretic medications. Use cautiously if you have gallbladder issues.'],
        ['Elderberry', 'Sambucus nigra', 'Elderberry is highly effective for immune support, particularly for cold and flu symptoms. It has antiviral properties.', '/images/herbs/elderberry.jpg', 'Syrup: Take 1-2 tablespoons daily. Tea: Steep 1-2 teaspoons of dried berries in hot water. Capsules: Follow product instructions.', 'Syrup: 1-2 tablespoons (15-30 ml) daily for prevention, up to 4 times daily during illness. Tea: 2-3 cups daily. Best taken at first sign of symptoms.', 'Raw berries are toxic - only use cooked or processed products. May interact with immunosuppressant medications. Use cautiously if you have autoimmune conditions.'],
        ['Milk Thistle', 'Silybum marianum', 'Milk thistle is renowned for its liver-protective properties. It supports liver detoxification and helps protect liver cells from damage.', '/images/herbs/milk-thistle.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml three times daily. Tea: Steep 1-2 teaspoons of seeds in hot water for 10-15 minutes.', 'Capsules: 150-300 mg of silymarin extract, 2-3 times daily. Tincture: 2-4 ml (40-80 drops) three times daily. Tea: 2-3 cups daily.', 'Generally safe for most adults. May cause mild digestive upset. Use cautiously if you have ragweed allergies.'],
        ['St. John\'s Wort', 'Hypericum perforatum', 'St. John\'s Wort is commonly used for mild to moderate depression and mood support. It has been studied extensively for mental wellness.', '/images/herbs/st-johns-wort.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Tea: Steep 1-2 teaspoons of dried flowers in hot water.', 'Capsules: 300-600 mg standardized extract, 2-3 times daily. Tincture: 2-4 ml daily. Tea: 2-3 cups daily. Takes 4-6 weeks to see effects.', 'May interact with many medications including antidepressants, birth control, and blood thinners. Not recommended during pregnancy. May cause photosensitivity.'],
        ['Ginkgo Biloba', 'Ginkgo biloba', 'Ginkgo biloba is known for supporting cognitive function, memory, and circulation. It is one of the oldest living tree species.', '/images/herbs/ginkgo-biloba.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Extract: Standardized extract is most effective.', 'Capsules: 120-240 mg standardized extract daily, divided into 2-3 doses. Tincture: 2-4 ml daily. Takes several weeks to see benefits.', 'May increase bleeding risk. Avoid before surgery. May interact with blood-thinning medications. May cause headaches or digestive upset in some.'],
        ['Ginseng', 'Panax ginseng', 'Ginseng is an adaptogenic herb that supports energy, stamina, and overall vitality. It helps the body adapt to stress.', '/images/herbs/ginseng.jpg', 'Tea: Steep 1-2 grams of root slices in hot water for 10-15 minutes. Capsules: Follow product instructions. Tincture: 2-4 ml daily.', 'Tea: 1-2 cups daily. Capsules: 200-400 mg standardized extract daily. Tincture: 2-4 ml daily. Use in cycles (2-3 weeks on, 1-2 weeks off).', 'May increase blood pressure. May interact with blood-thinning medications and diabetes medications. Not recommended during pregnancy. May cause insomnia if taken late in day.'],
        ['Rhodiola', 'Rhodiola rosea', 'Rhodiola is an adaptogenic herb that helps combat fatigue and stress. It supports mental performance and physical endurance.', '/images/herbs/rhodiola.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Extract: Standardized extract is preferred.', 'Capsules: 200-400 mg standardized extract daily, taken in morning. Tincture: 2-4 ml daily. Best taken on empty stomach.', 'May cause jitteriness or insomnia if taken late in day. May interact with antidepressants. Generally safe for most adults.'],
        ['Licorice Root', 'Glycyrrhiza glabra', 'Licorice root soothes the digestive system and supports respiratory health. It has anti-inflammatory and expectorant properties.', '/images/herbs/licorice-root.jpg', 'Tea: Steep 1-2 teaspoons of root in hot water for 10-15 minutes. Tincture: 2-4 ml daily. DGL tablets: Chewable form for digestive support.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml daily. DGL: 300-400 mg, 3 times daily before meals. Limit use to 4-6 weeks.', 'May raise blood pressure with long-term use. Avoid if you have high blood pressure, heart disease, or kidney disease. DGL form is safer for extended use.'],
        ['Marshmallow Root', 'Althaea officinalis', 'Marshmallow root is a demulcent herb that soothes irritated tissues. It is excellent for digestive and respiratory comfort.', '/images/herbs/marshmallow-root.jpg', 'Tea: Cold infusion - steep 1-2 teaspoons in cold water overnight. Tincture: 2-4 ml three times daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml (40-80 drops) three times daily. Capsules: 500-1000 mg, 3 times daily.', 'May slow absorption of other medications - take 1 hour before or after other medications. Generally very safe.'],
        ['Slippery Elm', 'Ulmus rubra', 'Slippery elm is a soothing demulcent that coats and protects irritated tissues in the digestive and respiratory tracts.', '/images/herbs/slippery-elm.jpg', 'Powder: Mix 1-2 teaspoons in water or juice. Capsules: Follow product instructions. Lozenges: For throat irritation.', 'Powder: 1-2 teaspoons, 3-4 times daily mixed in liquid. Capsules: 400-500 mg, 3-4 times daily. Take with plenty of water.', 'May slow absorption of medications - take 1-2 hours before or after other medications. Generally very safe and gentle.'],
        ['Fennel', 'Foeniculum vulgare', 'Fennel supports digestive health and can help relieve gas, bloating, and indigestion. It has a pleasant licorice-like flavor.', '/images/herbs/fennel.jpg', 'Tea: Steep 1-2 teaspoons of seeds in hot water for 10 minutes. Chew seeds after meals. Essential oil: Dilute for topical use.', 'Tea: 1-3 cups daily, especially after meals. Seeds: Chew 1/2 to 1 teaspoon after meals. Essential oil: Use sparingly, always diluted.', 'Generally safe. May cause allergic reactions in people sensitive to celery or carrots. Use cautiously during pregnancy.'],
        ['Fenugreek', 'Trigonella foenum-graecum', 'Fenugreek supports blood sugar regulation and can help with digestive issues. It is also used to support lactation.', '/images/herbs/fenugreek.jpg', 'Tea: Steep 1-2 teaspoons of seeds in hot water. Capsules: Follow product instructions. Seeds: Can be sprouted or cooked.', 'Tea: 2-3 cups daily. Capsules: 500-1000 mg, 2-3 times daily. Seeds: 1-2 teaspoons daily. Best taken with meals.', 'May lower blood sugar - monitor if diabetic. May interact with diabetes medications. Not recommended during pregnancy. May cause maple syrup-like odor in urine.'],
        ['Burdock Root', 'Arctium lappa', 'Burdock root supports liver health and skin conditions. It acts as a gentle blood purifier and supports detoxification.', '/images/herbs/burdock-root.jpg', 'Tea: Simmer 1-2 teaspoons of dried root in water for 15-20 minutes. Tincture: 2-4 ml three times daily. Can be cooked as food.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml (40-80 drops) three times daily. Fresh root: Can be cooked and eaten as vegetable.', 'May cause allergic reactions in people sensitive to ragweed. May interact with diuretic medications. Generally safe when used appropriately.'],
        ['Nettle', 'Urtica dioica', 'Nettle is a nutrient-rich herb that supports overall health. It is excellent for allergies, inflammation, and as a general tonic.', '/images/herbs/nettle.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 10-15 minutes. Tincture: 2-4 ml three times daily. Capsules: Follow product instructions.', 'Tea: 2-4 cups daily. Tincture: 2-4 ml (40-80 drops) three times daily. Capsules: 300-600 mg, 2-3 times daily.', 'Fresh plant can cause skin irritation - only use dried or cooked. May interact with blood-thinning medications. Generally safe when processed.'],
        ['Red Clover', 'Trifolium pratense', 'Red clover is rich in isoflavones and supports women\'s health, particularly during menopause. It also supports skin health.', '/images/herbs/red-clover.jpg', 'Tea: Steep 1-2 teaspoons of dried flowers in hot water for 10-15 minutes. Tincture: 2-4 ml daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml daily. Capsules: 40-80 mg isoflavones daily. Best used consistently for several weeks.', 'May interact with blood-thinning medications. Not recommended during pregnancy or breastfeeding. May affect hormone-sensitive conditions.'],
        ['Saw Palmetto', 'Serenoa repens', 'Saw palmetto is primarily used to support prostate health in men. It may help with urinary symptoms related to prostate enlargement.', '/images/herbs/saw-palmetto.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Extract: Standardized extract is most effective.', 'Capsules: 320 mg standardized extract daily, divided into 2 doses. Tincture: 2-4 ml daily. Takes 4-6 weeks to see benefits.', 'May interact with hormone medications. May affect blood clotting. Generally safe for most men. Not recommended for women or children.'],
        ['Cranberry', 'Vaccinium macrocarpon', 'Cranberry is well-known for supporting urinary tract health. It helps prevent bacteria from adhering to urinary tract walls.', '/images/herbs/cranberry.jpg', 'Juice: Drink unsweetened cranberry juice. Capsules: Follow product instructions. Dried berries: Add to food or eat as snack.', 'Juice: 8-16 oz unsweetened juice daily. Capsules: 300-400 mg extract, 2-3 times daily. Dried: 1/4 to 1/2 cup daily.', 'May interact with blood-thinning medications. High sugar content in sweetened juices may be problematic. Generally safe.'],
        ['Uva Ursi', 'Arctostaphylos uva-ursi', 'Uva ursi is a traditional remedy for urinary tract infections. It has antimicrobial properties that support urinary health.', '/images/herbs/uva-ursi.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 10-15 minutes. Tincture: 2-4 ml three times daily.', 'Tea: 2-3 cups daily for short-term use (up to 1 week). Tincture: 2-4 ml (40-80 drops) three times daily. Not for long-term use.', 'Not for long-term use - limit to 1 week. Not recommended during pregnancy or breastfeeding. May cause stomach upset. Requires alkaline urine to be effective.'],
        ['Bilberry', 'Vaccinium myrtillus', 'Bilberry supports eye health and vision. It is rich in antioxidants and may help with night vision and eye strain.', '/images/herbs/bilberry.jpg', 'Capsules: Follow product instructions. Tea: Steep 1-2 teaspoons of dried berries in hot water. Fresh or frozen berries: Eat as food.', 'Capsules: 80-160 mg standardized extract, 2-3 times daily. Tea: 2-3 cups daily. Fresh: 1/2 to 1 cup daily.', 'May interact with blood-thinning medications. Generally safe. May lower blood sugar slightly.'],
        ['Hawthorn', 'Crataegus monogyna', 'Hawthorn is a cardiovascular tonic that supports heart health. It helps improve circulation and supports healthy blood pressure.', '/images/herbs/hawthorn.jpg', 'Tea: Steep 1-2 teaspoons of berries or flowers in hot water for 10-15 minutes. Tincture: 2-4 ml three times daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml (40-80 drops) three times daily. Capsules: 300-600 mg, 2-3 times daily. Takes several weeks to see benefits.', 'May interact with heart medications - consult healthcare provider. May cause mild digestive upset. Generally safe when used appropriately.'],
        ['Motherwort', 'Leonurus cardiaca', 'Motherwort supports cardiovascular health and helps with anxiety and stress. It has calming properties and supports women\'s health.', '/images/herbs/motherwort.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 10-15 minutes. Tincture: 2-4 ml three times daily.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml (40-80 drops) three times daily. Best taken consistently for several weeks.', 'Not recommended during pregnancy - may stimulate uterine contractions. May interact with blood-thinning medications. Generally safe for most adults.'],
        ['Yarrow', 'Achillea millefolium', 'Yarrow is a versatile herb that supports wound healing, reduces bleeding, and helps with fevers. It has astringent and anti-inflammatory properties.', '/images/herbs/yarrow.jpg', 'Tea: Steep 1-2 teaspoons of dried flowers in hot water for 10-15 minutes. Tincture: 2-4 ml three times daily. Topical: Use as compress for wounds.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml (40-80 drops) three times daily. Topical: Apply as needed to wounds.', 'May cause allergic reactions in people sensitive to ragweed. May increase bleeding risk. Not recommended during pregnancy.'],
        ['Calendula', 'Calendula officinalis', 'Calendula is excellent for skin healing and wound care. It has anti-inflammatory and antimicrobial properties that support skin health.', '/images/herbs/calendula.jpg', 'Topical: Apply cream, ointment, or infused oil to affected areas. Tea: Steep 1-2 teaspoons of flowers for internal use. Tincture: 2-4 ml daily.', 'Topical: Apply 2-3 times daily to wounds or skin irritation. Tea: 2-3 cups daily. Tincture: 2-4 ml daily.', 'May cause allergic reactions in people sensitive to ragweed or daisies. Generally very safe for topical use.'],
        ['Comfrey', 'Symphytum officinale', 'Comfrey is traditionally used for wound healing and bone support. It should only be used topically due to safety concerns with internal use.', '/images/herbs/comfrey.jpg', 'Topical only: Apply cream, ointment, or poultice to affected areas. Do not use internally.', 'Topical: Apply 2-3 times daily to wounds, bruises, or sprains. For external use only.', 'Do not use internally - contains compounds that can be toxic to the liver. Topical use should be limited to unbroken skin. Not recommended during pregnancy.'],
        ['Plantain', 'Plantago major', 'Plantain is a common weed with excellent wound-healing properties. It can be used fresh or dried for skin irritation and bug bites.', '/images/herbs/plantain.jpg', 'Fresh: Crush leaves and apply directly to skin. Tea: Steep 1-2 teaspoons of dried leaves. Tincture: 2-4 ml daily.', 'Topical: Apply fresh leaves as poultice as needed. Tea: 2-3 cups daily. Tincture: 2-4 ml daily.', 'Generally very safe. May cause mild allergic reactions in sensitive individuals.'],
        ['Eucalyptus', 'Eucalyptus globulus', 'Eucalyptus is excellent for respiratory support. It helps clear congestion and supports breathing. Essential oil is commonly used.', '/images/herbs/eucalyptus.jpg', 'Essential oil: Use in steam inhalation or diffuser. Tea: Steep 1-2 teaspoons of leaves. Topical: Dilute oil for chest rubs.', 'Essential oil: 2-4 drops in steam inhalation or diffuser. Tea: 2-3 cups daily. Topical: Always dilute - never use undiluted.', 'Essential oil is toxic if ingested. Keep away from children and pets. May cause skin irritation if not properly diluted.'],
        ['Thyme', 'Thymus vulgaris', 'Thyme has antimicrobial properties and supports respiratory health. It is excellent for coughs and respiratory infections.', '/images/herbs/thyme.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 10 minutes. Essential oil: Use in steam inhalation. Add to food.', 'Tea: 2-4 cups daily. Essential oil: 2-3 drops in steam inhalation. Culinary: Use liberally in cooking.', 'Essential oil should not be ingested. Generally safe in culinary amounts. May cause allergic reactions in sensitive individuals.'],
        ['Oregano', 'Origanum vulgare', 'Oregano has strong antimicrobial properties and supports immune health. It is rich in antioxidants and supports digestive health.', '/images/herbs/oregano.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves. Essential oil: Use in steam inhalation or dilute for topical use. Add to food.', 'Tea: 2-3 cups daily. Essential oil: 2-3 drops in steam inhalation. Culinary: Use in cooking regularly.', 'Essential oil is very strong and should be used sparingly. May cause skin irritation if not properly diluted. Generally safe in culinary amounts.'],
        ['Rosemary', 'Rosmarinus officinalis', 'Rosemary supports cognitive function and memory. It also has antimicrobial properties and supports circulation.', '/images/herbs/rosemary.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water. Essential oil: Use in aromatherapy. Add to food.', 'Tea: 2-3 cups daily. Essential oil: 2-4 drops in diffuser. Culinary: Use regularly in cooking.', 'May increase blood pressure in some individuals. Essential oil should not be ingested. Generally safe in culinary amounts.'],
        ['Sage', 'Salvia officinalis', 'Sage supports memory and cognitive function. It also has antimicrobial properties and is excellent for sore throats.', '/images/herbs/sage.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves for gargling or drinking. Essential oil: Use in steam inhalation. Add to food.', 'Tea: Gargle 2-3 times daily for sore throat, or drink 1-2 cups daily. Essential oil: 2-3 drops in steam. Culinary: Use in cooking.', 'Contains thujone - avoid high doses. Not recommended during pregnancy or breastfeeding. May lower blood sugar.'],
        ['Catnip', 'Nepeta cataria', 'Catnip is calming and supports digestive health. It is gentle and safe for children. It also helps with sleep and anxiety.', '/images/herbs/catnip.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 10 minutes. Tincture: 2-4 ml daily.', 'Tea: 1-3 cups daily, especially before bedtime. Tincture: 2-4 ml (40-80 drops) daily. Safe for children in smaller doses.', 'Generally very safe and gentle. May cause mild drowsiness. Safe for children when used appropriately.'],
        ['Lemon Balm', 'Melissa officinalis', 'Lemon balm is calming and supports mood. It helps with anxiety, sleep, and digestive issues. It has a pleasant lemon scent.', '/images/herbs/lemon-balm.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 10 minutes. Tincture: 2-4 ml daily. Fresh: Add to salads or drinks.', 'Tea: 2-4 cups daily, especially before bedtime. Tincture: 2-4 ml daily. Fresh: Use liberally in food and drinks.', 'May interact with thyroid medications. Generally very safe. May cause mild drowsiness.'],
        ['Passionflower', 'Passiflora incarnata', 'Passionflower is excellent for anxiety and sleep support. It has calming properties and helps promote restful sleep.', '/images/herbs/passionflower.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves and flowers in hot water for 10-15 minutes. Tincture: 2-4 ml before bedtime.', 'Tea: 1-2 cups 30-60 minutes before bedtime. Tincture: 2-4 ml (40-80 drops) before sleep. Can be combined with other calming herbs.', 'May cause drowsiness. May interact with sedatives and blood-thinning medications. Generally safe when used appropriately.'],
        ['Skullcap', 'Scutellaria lateriflora', 'Skullcap is a nervine herb that supports the nervous system. It helps with anxiety, stress, and promotes calm.', '/images/herbs/skullcap.jpg', 'Tea: Steep 1-2 teaspoons of dried leaves in hot water for 10-15 minutes. Tincture: 2-4 ml three times daily.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml (40-80 drops) three times daily. Best taken consistently for several weeks.', 'May cause drowsiness. May interact with sedatives. Generally safe when used appropriately.'],
        ['Hops', 'Humulus lupulus', 'Hops is well-known for its sedative properties. It supports sleep and helps with anxiety and restlessness.', '/images/herbs/hops.jpg', 'Tea: Steep 1-2 teaspoons of dried flowers in hot water for 10 minutes. Tincture: 2-4 ml before bedtime. Pillow: Place dried hops in pillow.', 'Tea: 1 cup 30-60 minutes before bedtime. Tincture: 2-4 ml (40-80 drops) before sleep. Pillow: Place in sachet near bed.', 'May cause drowsiness. Not recommended during pregnancy or if you have depression. May interact with sedatives.'],
        ['Black Cohosh', 'Actaea racemosa', 'Black cohosh is primarily used for women\'s health, particularly for menopausal symptoms. It supports hormonal balance.', '/images/herbs/black-cohosh.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Extract: Standardized extract is preferred.', 'Capsules: 20-40 mg standardized extract, 2 times daily. Tincture: 2-4 ml daily. Use for 6 months or less.', 'May interact with hormone medications. May cause liver issues in rare cases. Not recommended during pregnancy. Monitor liver function with extended use.'],
        ['Dong Quai', 'Angelica sinensis', 'Dong quai is a traditional Chinese herb for women\'s health. It supports menstrual health and hormonal balance.', '/images/herbs/dong-quai.jpg', 'Tea: Simmer 1-2 teaspoons of root in water for 15-20 minutes. Tincture: 2-4 ml daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml daily. Capsules: 500-1000 mg daily. Best used in cycles with menstrual cycle.', 'May increase bleeding risk. Not recommended during pregnancy. May interact with blood-thinning medications. May cause photosensitivity.'],
        ['Vitex', 'Vitex agnus-castus', 'Vitex, also known as chasteberry, supports women\'s hormonal health. It helps balance hormones and supports menstrual health.', '/images/herbs/vitex.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Extract: Standardized extract is preferred.', 'Capsules: 200-400 mg standardized extract daily. Tincture: 2-4 ml daily. Takes 3-6 months to see full benefits.', 'May interact with hormone medications and birth control. Not recommended during pregnancy. May cause mild digestive upset.'],
        ['Maca', 'Lepidium meyenii', 'Maca is an adaptogenic root that supports energy, stamina, and hormonal balance. It is particularly popular for libido support.', '/images/herbs/maca.jpg', 'Powder: Mix 1-2 teaspoons in smoothies, drinks, or food. Capsules: Follow product instructions.', 'Powder: 1-3 teaspoons (3-9 grams) daily. Capsules: 1500-3000 mg daily. Best taken consistently for several weeks.', 'May affect hormone levels. Use cautiously if you have hormone-sensitive conditions. Generally safe for most adults.'],
        ['Tribulus', 'Tribulus terrestris', 'Tribulus is used to support libido and athletic performance. It may help with energy and vitality.', '/images/herbs/tribulus.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Extract: Standardized extract is preferred.', 'Capsules: 250-500 mg standardized extract, 2-3 times daily. Tincture: 2-4 ml daily. Use in cycles.', 'May interact with diabetes medications. May affect hormone levels. Not recommended during pregnancy.'],
        ['Horny Goat Weed', 'Epimedium grandiflorum', 'Horny goat weed is traditionally used to support libido and sexual function. It may also support bone health.', '/images/herbs/horny-goat-weed.jpg', 'Capsules: Follow product instructions. Tincture: 2-4 ml daily. Tea: Steep 1-2 teaspoons of leaves.', 'Capsules: 500-1000 mg daily. Tincture: 2-4 ml daily. Tea: 2-3 cups daily. Takes several weeks to see benefits.', 'May interact with blood-thinning medications. May cause dizziness or dry mouth. Not recommended during pregnancy.'],
        ['Shatavari', 'Asparagus racemosus', 'Shatavari is an Ayurvedic herb that supports women\'s health, particularly reproductive health and lactation. It is adaptogenic.', '/images/herbs/shatavari.jpg', 'Powder: Mix 1-2 teaspoons in warm milk or water. Capsules: Follow product instructions. Tincture: 2-4 ml daily.', 'Powder: 1-3 grams daily. Capsules: 500-1000 mg daily. Tincture: 2-4 ml daily. Best taken consistently.', 'May affect hormone levels. Use cautiously if you have hormone-sensitive conditions. Generally safe for most adults.'],
        ['Reishi Mushroom', 'Ganoderma lucidum', 'Reishi is a medicinal mushroom known as the "mushroom of immortality." It supports immune function and overall wellness.', '/images/herbs/reishi.jpg', 'Tea: Simmer 1-2 teaspoons of dried mushroom slices for 1-2 hours. Capsules: Follow product instructions. Extract: Tincture or powder.', 'Tea: 2-3 cups daily. Capsules: 1-3 grams daily. Extract: Follow product instructions. Best taken consistently.', 'May interact with immunosuppressant medications. May cause dizziness or digestive upset in some. Generally safe.'],
        ['Chaga Mushroom', 'Inonotus obliquus', 'Chaga is a powerful medicinal mushroom rich in antioxidants. It supports immune function and overall health.', '/images/herbs/chaga.jpg', 'Tea: Simmer 1-2 teaspoons of chunks for 1-2 hours. Powder: Mix in drinks. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Powder: 1-2 grams daily. Capsules: 500-1000 mg daily. Best taken consistently.', 'May interact with blood-thinning medications. May interact with diabetes medications. Generally safe when used appropriately.'],
        ['Lion\'s Mane', 'Hericium erinaceus', 'Lion\'s Mane is a medicinal mushroom that supports cognitive function and nerve health. It may help with memory and focus.', '/images/herbs/lions-mane.jpg', 'Capsules: Follow product instructions. Tea: Simmer dried mushroom. Powder: Mix in drinks or food.', 'Capsules: 500-3000 mg daily. Tea: 2-3 cups daily. Powder: 1-3 grams daily. Takes several weeks to see benefits.', 'May interact with blood-thinning medications. Generally safe. May cause mild digestive upset in some individuals.'],
        ['Cordyceps', 'Cordyceps sinensis', 'Cordyceps is a medicinal mushroom that supports energy, athletic performance, and respiratory health. It is adaptogenic.', '/images/herbs/cordyceps.jpg', 'Capsules: Follow product instructions. Tea: Simmer dried cordyceps. Powder: Mix in drinks.', 'Capsules: 1-3 grams daily. Tea: 2-3 cups daily. Powder: 1-3 grams daily. Best taken consistently for several weeks.', 'May interact with immunosuppressant medications. May affect blood sugar. Generally safe when used appropriately.'],
        ['Schisandra', 'Schisandra chinensis', 'Schisandra is an adaptogenic berry that supports energy, mental performance, and liver health. It helps the body adapt to stress.', '/images/herbs/schisandra.jpg', 'Tea: Steep 1-2 teaspoons of dried berries in hot water. Tincture: 2-4 ml daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml daily. Capsules: 500-2000 mg daily. Best taken consistently.', 'May interact with medications metabolized by the liver. May cause mild digestive upset. Generally safe for most adults.'],
        ['Astragalus', 'Astragalus membranaceus', 'Astragalus is an adaptogenic herb that supports immune function and overall vitality. It helps the body resist stress and illness.', '/images/herbs/astragalus.jpg', 'Tea: Simmer 1-2 teaspoons of sliced root for 20-30 minutes. Tincture: 2-4 ml daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml daily. Capsules: 500-1000 mg daily. Best taken consistently for immune support.', 'May interact with immunosuppressant medications. May interact with blood-thinning medications. Generally safe when used appropriately.'],
        ['Rehmannia', 'Rehmannia glutinosa', 'Rehmannia is a traditional Chinese herb that supports kidney health and hormonal balance. It is nourishing and tonifying.', '/images/herbs/rehmannia.jpg', 'Tea: Simmer 1-2 teaspoons of root for 20-30 minutes. Tincture: 2-4 ml daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml daily. Capsules: 500-1000 mg daily. Best used in traditional formulas.', 'May interact with diabetes medications. May affect blood sugar. Generally safe when used appropriately.'],
        ['He Shou Wu', 'Polygonum multiflorum', 'He Shou Wu is a traditional Chinese herb that supports hair health, liver function, and overall vitality. It is considered a longevity herb.', '/images/herbs/he-shou-wu.jpg', 'Tea: Simmer 1-2 teaspoons of root for 20-30 minutes. Tincture: 2-4 ml daily. Capsules: Follow product instructions.', 'Tea: 2-3 cups daily. Tincture: 2-4 ml daily. Capsules: 500-1000 mg daily. Takes several months to see benefits.', 'May cause liver toxicity in some individuals - monitor liver function. May interact with liver medications. Use processed/steamed form when possible.']
    ];
    
    $inserted = 0;
    $skipped = 0;
    $errors = [];
    
    $stmt = $db->prepare("INSERT IGNORE INTO herbs (name, scientific_name, description, image_url, preparation_methods, dosage_info, safety_warnings) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    foreach ($herbs as $herb) {
        try {
            $result = $stmt->execute($herb);
            if ($stmt->rowCount() > 0) {
                $inserted++;
            } else {
                $skipped++;
            }
        } catch (PDOException $e) {
            $errors[] = "Error inserting {$herb[0]}: " . $e->getMessage();
        }
    }
    
    // Count after insertion
    $stmt = $db->query("SELECT COUNT(*) as count FROM herbs");
    $afterCount = (int)$stmt->fetch(PDO::FETCH_ASSOC)['count'];
    
} catch (PDOException $e) {
    die("Database error: " . $e->getMessage());
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insert All Herbs - Herbal Haven</title>
    <link rel="stylesheet" href="<?php echo SITE_URL; ?>/css/style.css">
</head>
<body>
    <div class="container" style="max-width: 800px; margin: 2rem auto;">
        <h1 style="color: var(--primary-green); margin-bottom: 2rem;">🌿 Insert All Herbs</h1>
        
        <div class="alert alert-success" style="margin-bottom: 2rem;">
            <h2>Insertion Complete!</h2>
            <p><strong>Before:</strong> <?php echo $beforeCount; ?> herbs</p>
            <p><strong>After:</strong> <?php echo $afterCount; ?> herbs</p>
            <p><strong>Newly inserted:</strong> <?php echo $inserted; ?> herbs</p>
            <p><strong>Skipped (already exist):</strong> <?php echo $skipped; ?> herbs</p>
            <?php if ($afterCount == 63): ?>
                <p style="color: var(--primary-green); font-weight: bold; margin-top: 1rem;">✅ All 63 herbs are now in the database!</p>
            <?php else: ?>
                <p style="color: var(--warning-orange); font-weight: bold; margin-top: 1rem;">⚠️ Expected 63 herbs, but found <?php echo $afterCount; ?>.</p>
            <?php endif; ?>
        </div>
        
        <?php if (!empty($errors)): ?>
        <div class="alert alert-danger" style="margin-bottom: 2rem;">
            <h3>Errors:</h3>
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?php echo htmlspecialchars($error); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
        
        <div style="margin-top: 2rem;">
            <a href="<?php echo SITE_URL; ?>/verify-herbs.php" class="btn btn-secondary">Verify Herbs</a>
            <a href="<?php echo SITE_URL; ?>/setup.php" class="btn btn-secondary" style="margin-left: 0.5rem;">Setup Page</a>
            <a href="<?php echo SITE_URL; ?>/catalogue.php" class="btn btn-primary" style="margin-left: 0.5rem;">View Catalogue</a>
        </div>
    </div>
</body>
</html>

